window.SKANOWSKI_TOURS = [
  {
    id: "zielona",
    kicker: "01 / 03",
    title: "Jesienny szlak",
    place: "Nadleśnictwo Zielona Góra · Lasy Państwowe",
    copy: "Liście, światło, wąska nić ścieżki. Kadr, od którego zaczyna się wirtualna lekcja w terenie — jeszcze zanim ktoś dojdzie do pierwszej tablicy.",
    pano: "assets/tour-zielona.jpg",
    maps: "https://maps.app.goo.gl/nxefdYR7dACwcZRd8",
    lat: 51.9216693,
    lng: 15.4712135,
    heading: 137.82,
  },
  {
    id: "smolarnia",
    kicker: "02 / 03",
    title: "Pomost i tafla",
    place: "Smolarnia · 64-980 · Puszcza Notecka",
    copy: "Drewniany pomost, ławki, tafla jeziora. Punkt, w którym ścieżka przestaje być korytarzem między drzewami i staje się widokiem.",
    pano: "assets/tour-smolarnia.jpg",
    maps: "https://maps.app.goo.gl/k4Xvu9pEimKkro5A8",
    lat: 53.0258385,
    lng: 16.3596657,
    heading: 311.35,
  },
  {
    id: "tablica",
    kicker: "03 / 03",
    title: "Tablica „Grzyby”",
    place: "Nadleśnictwo Zielona Góra · ścieżka dydaktyczna",
    copy: "Przystanek z treścią: jadalne, trujące, budowa grzyba. Wirtualny spacer po to, żeby tablicę dało się przeczytać — nie tylko minąć.",
    pano: "assets/tour-tablica.jpg",
    maps: "https://maps.app.goo.gl/mA3mbW9VHLFQvKkT8",
    lat: 51.9233751,
    lng: 15.4780809,
    heading: 331.65,
  },
];
